packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  '@parcel/watcher': true
  argon2: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
  msgpackr-extract: true
