export const brand = {
  name: 'BotHub',
  tagline: 'Conversas que aproximam.',
  logo: 'bot',
  colors: {
    primary: '#6366F1',
    primaryText: '#4F46E5',
    darkPrimaryText: '#A5B4FC',
    ctaStart: '#4F46E5',
    ctaEnd: '#7C3AED',
    dangerText: '#DC2626',
    darkDangerText: '#FCA5A5',
    accent: '#8B5CF6',
    background: '#F8FAFC',
    dark: '#0B1020',
    success: '#22C55E',
    warning: '#F59E0B',
    danger: '#EF4444',
    whatsapp: '#25D366',
    telegram: '#26A5E4',
    sms: '#EC4899',
  },
  defaults: { locale: 'pt-BR', currency: 'BRL', timeZone: 'America/Sao_Paulo' },
} as const;
